twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch

  welcome-message: Welcome brother
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 10
  mock-sleep-ms: 1000
